# 开发环境配置文件

server:
  port: 8088
  max-http-header-size: 10240

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    druid:
      driver-class-name:  com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://82.157.246.141:3306/cos_db?serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL&useUnicode=true&characterEncoding=UTF-8     # 数据库链接
      username: cos_db
      password: XPrayCTr6nBkaAFz

minio:
  url: http://82.157.246.141:9000
  access: minio
  secret-key: minio@123
  back-ground-bucket-name: back-ground-bucket
  cos-img-bucket-name: cos-img-bucket
  chunk_size: 5242880
  expire_time: 600000
  default-folder-zip: dataset-zip
  default-folder-info: dataset-info



